In [ ]:
import torch
import torch.nn as nn

1 Neuron Only

In [ ]:
class Model(nn.Module):

    def __init__(self, num_feats):
        super().__init__()
        self.linear = nn.Linear(num_feats, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [ ]:
features = torch.rand(10, 5)

In [ ]:
model = Model(features.shape[1])

model(features)


tensor([[0.5193],
        [0.5058],
        [0.5495],
        [0.5742],
        [0.5717],
        [0.5864],
        [0.4954],
        [0.5428],
        [0.5295],
        [0.5594]], grad_fn=<SigmoidBackward0>)

In [ ]:
# !pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

5 input neurons, 3 hidden neurosn

In [ ]:
class Model(nn.Module):

    def __init__(self, num_feats):
        super().__init__()
        self.linear = nn.Linear(num_feats, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()


    def forward(self, features):
        out = self.linear(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [ ]:
model = Model(features.shape[1])

model(features)


tensor([[0.4233],
        [0.4223],
        [0.4183],
        [0.4289],
        [0.4115],
        [0.4115],
        [0.4234],
        [0.4131],
        [0.4326],
        [0.4129]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.2132,  0.1271,  0.0160, -0.2540, -0.2042],
        [-0.2304, -0.0789,  0.2942,  0.0085,  0.1971],
        [-0.2979,  0.3454, -0.2621, -0.3471,  0.4290]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[0.2126, 0.3881, 0.1162]], requires_grad=True)

In [ ]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [ ]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4723],
        [0.4281],
        [0.4836],
        [0.4448],
        [0.4904],
        [0.4730],
        [0.4889],
        [0.4834],
        [0.4617],
        [0.4904]], grad_fn=<SigmoidBackward0>)

In [ ]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00